name: Hamekoz

on:
  pull_request:
    branches: ["main"]
  push:
    branches: ["main"]
    tags:
      - v*.*.*

jobs:
  conventional-commits:
    name: Conventional Commits
    uses: hamekoz/.github/.github/workflows/conventional-commits.yml@main
  continuous-integration:
    name: Continuous Integration
    needs: conventional-commits
    uses: hamekoz/.github/.github/workflows/dotnet.yml@main
  continuous-delivery:
    if: ${{ github.event_name == 'push' }}
    name: Continuous Delivery
    needs: [conventional-commits, continuous-integration]
    uses: hamekoz/.github/.github/workflows/continuous-delivery-nuget.yml@main
    secrets: inherit
